language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO=""   # no django
  - DJANGO=1.11
  - DJANGO=2.0

install:
  - pip install -e .
  - pip install -e '.[test]'
  - if [ ! -z $DJANGO ]; then pip install -q $DJANGO; fi
  - if [ $DJANGO != '' ]; then pip install django-autocomplete-light pytest-django; fi
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - py.test --cov=viapy

after_success:
  - codecov
