name: unit tests

on:
  push: # run on all branches
  pull_request:
    branches: [develop, main]
  schedule: # run automatically on main branch each Tuesday at 11am
    - cron: "0 16 * * 2"

jobs:
  python-unit:
    name: Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]
        django: [0, "3.2", "4.0", "4.1", "4.2", "5.0"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv and Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Install package dependencies
        run: >-
          if [ "${{ matrix.django }}" -gt "0" ]; then
            uv add django=="${{ matrix.django }}";
            uv sync --extra test --extra django_test;
          else
            uv sync --extra test;
          fi

      - name: Setup test settings
        run: |
          cp ci/testsettings.py testsettings.py
          python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

      - name: Run pytest
        run: uv run pytest --cov=viapy --cov=tests --cov-report=xml --cov-report=term

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
